package com.example.demo001.domain.Factory;

import com.example.demo001.domain.Transport.City;
import lombok.Data;
import javax.persistence.*;
import java.util.List;

/**
 * Representation of physical factory
 * - describes basic information, identifies warehouses and user responsible for managing it
 */
@Entity
@Data
public class Factory {

    /** Factory's autogenerated unique identification number */
    @Id
    @GeneratedValue
    private long factoryId;

    /** Name of the factory */
    @Column
    private String factoryName;

    /** List of products which factories produce (treated like warehouses) */
    @OneToMany(fetch = FetchType.EAGER)
    private List<ProductionAbility> producedProducts;

    /** City in which factory is located */
    @OneToOne
    private City factoryLocation;

    /** User responsible for managing the factory */
    @OneToOne
    private FactoryManager factoryManager;

    public Factory() {}
    public Factory(String factoryName)
    {
        this.factoryName = factoryName;
    }
}
