package com.example.demo001.domain.Factory;

import com.example.demo001.domain.Products.Product;
import lombok.Data;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import javax.persistence.*;

/**
 * Representation of factory's warehouse
 * - determines produced product and its available amounts.
 */
@Entity
@Data
public class ProductionAbility {

    /** Warehouse's autogenerated unique identification number */
    @Id
    @GeneratedValue
    private long id;

    /** Product produced by factory, stored in the warehouse */
    @OneToOne
    @LazyCollection(LazyCollectionOption.FALSE)
    private Product myProduct;

    /** Factory producing and storing product */
   /* @OneToOne
    private Factory myFactory;*/

    /** Amount of the product stored in warehouse, available for sale */
    @Column
    private int productAmount;

    /** Amount of the product reserved by existing, not completed orders */
    @Column
    private int reservedProducts;

}
