package com.example.demo001.domain.OrderManagement;

import com.example.demo001.domain.Client.Client;
import com.example.demo001.domain.Transport.TransportProvider;
import lombok.Data;
import javax.persistence.*;
import java.util.*;

/**
 * Representation of order placed by the client
 * - determines order information and stores ordered items.
 */
@Entity
@Data
public class ProductOrder {

    /** Order's autogenerated unique identification number */
    @Id
    @GeneratedValue
    private long orderId;

    /** Order's status that classifies its stage of completion. */
    @Column
    private OrderStatus orderStatus;

    /** Client that placed the order */
    @OneToOne
    private Client orderClient;

    /** Transport provider assigned to deliver the order to client */
    @OneToOne
    private TransportProvider orderTransportProvider;

    /** List of ordered items */
    @OneToMany
    private List<OrderItem> orderedProducts = new ArrayList<>();

    public ProductOrder() {}
    public ProductOrder(Client orderClient) {
        this.orderStatus = OrderStatus.ISSUED;
        this.orderClient = orderClient;
        this.orderTransportProvider = null;
    }
}
