package com.example.demo001.domain.Actors;

import javax.persistence.*;

/**
 * Representation of user of the system
 * - describes basic information, role and whether given user is an active participant of system.
 */
@Entity
public abstract class BasicUser {

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public UserRole getUserRole() {
        return userRole;
    }

    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    /** User's autogenerated unique identification number */
    @Id
    @GeneratedValue
    protected long userId;

    /** Name of user used both as a display name and a part of authentication process */
    @Column
    protected String userName;

    /** Password of user user as a part of authentication process */
    @Column
    protected String userPassword;

    /** Role of user in the system describes type of user and his use cases */
    @Column
    protected UserRole userRole;

    /** Flag determining whether user's account is activated
     * (if account is deactivated then user can no longer use the system) */
    @Column
    protected boolean isActive;

    public BasicUser() {}
    BasicUser(String userName){
        this.userName = userName;
    }


}
